### PR TITLE
[RFC] neighbour solicitation via netlink

### PR DESCRIPTION
**Pull request by t-8ch**
This removes the hand-rolled icmp6 and arp implementations with a
netlink based one.
We should probably move this to a new component "neighbourmgr".

This is not tested in a real environment, as I am missing it atm.

### CODE REVIEW

**Comment by t-8ch** [comment]
Cc @christf

**Comment by christf** [comment]
Thank you for this patch. Unfortunately the current arp / icmp code does 
not only do sending of arp/icmp packets but also handling incoming 
requests as in 
https://github.com/freifunk-gluon/l3roamd/pull/18/files#diff-ee119d60e3b4d13d664f41c8e9da00b6L183

We will have to keep some of this code.



-- 
()  ascii ribbon campaign - against html e-mail
/\  against proprietary attachments

**Comment by t-8ch** [comment]
@christf Shouldn't this be also handled via netlink as in https://github.com/freifunk-gluon/l3roamd/blob/258270fa05ad65302bb471a0639d8d3b8910e2e7/src/routemgr.c#L104 ?

**Comment by christf** [comment]
if it can be handled by netlink then it should be part of this PR. So far I though this needed BPF.

**Comment by christf** [comment]
I just lookad at this again and tested it in my virtual environment. It seems to do what it is meant to do. \o/
Thank you for the patch. 
root@6xxxx-5254009dd24a:/etc/init.d# Thu Nov 23 19:16:41 2017 daemon.info l3roamd[27715]: Got packet to 2a06:8187:fbab:2:5054:ff:fe7d:a857
Thu Nov 23 19:16:41 2017 daemon.info l3roamd[27715]: Looking for 2a06:8187:fbab:2:5054:ff:fe7d:a857
Thu Nov 23 19:16:41 2017 daemon.info l3roamd[27715]: v6!
Thu Nov 23 19:16:41 2017 daemon.info l3roamd[27715]: sent packet to ff02::5523 on iface mesh-vpn rc: 38
Thu Nov 23 19:16:41 2017 daemon.info l3roamd[27715]: neighbour [00:00:00:00:00:00] changed on interface local-node
Thu Nov 23 19:16:41 2017 daemon.info l3roamd[27715]: Add Address: 2a06:8187:fbab:2:5054:ff:fe7d:a857 (MAC 00:00:00:00:00:00)
Thu Nov 23 19:16:41 2017 daemon.info l3roamd[27715]: 2a06:8187:fbab:2:5054:ff:fe7d:a857 changes from INACTIVE to ACTIVE
Thu Nov 23 19:16:41 2017 daemon.info l3roamd[27715]: sent packet to ff02::5523 on iface mesh-vpn rc: 28
Thu Nov 23 19:16:41 2017 daemon.info l3roamd[27715]: sent packet to ff02::5523 on iface mesh-vpn rc: 46
Thu Nov 23 19:16:41 2017 daemon.info l3roamd[27715]: neighbour [00:00:00:00:00:00] changed on interface local-node
Thu Nov 23 19:16:41 2017 daemon.info l3roamd[27715]: Add Address: 2a06:8187:fbab:2:5054:ff:fe7d:a857 (MAC 00:00:00:00:00:00)
Thu Nov 23 19:16:41 2017 daemon.info l3roamd[27715]: 2a06:8187:fbab:2:5054:ff:fe7d:a857 changes from ACTIVE to ACTIVE
Thu Nov 23 19:16:41 2017 daemon.info mmfd[1616]: parsing line: add xroute 2a06:8187:fbab:2:5054:ff:fe7d:a857/128-::/0 prefix 2a06:8187:fbab:2:5054:ff:fe7d:a857/128 from ::/0 metric 0
Thu Nov 23 19:16:41 2017 daemon.info fastd[1986]: resolving host `gw02.babel.ffffm.net' for peer <mesh_vpn_backbone_peer_fastd2>...
Thu Nov 23 19:16:43 2017 daemon.err mmfd[1616]: No data on babel socket within timeout of 2s.
Thu Nov 23 19:16:44 2017 daemon.info mmfd[1616]: Connecting to babeld
Thu Nov 23 19:16:44 2017 daemon.info mmfd[1616]: da
Thu Nov 23 19:16:44 2017 daemon.info mmfd[1616]: hier
Thu Nov 23 19:16:44 2017 daemon.err mmfd[1616]: Sending monitor comm


However we really need to support multiple client interfaces. For now, I guess we could get away with just using the bridge-interface to send the ns, however in the long run this will not be sufficient. 

Nevertheless I will merge this now, the old code does not support multiple interfaces either and I really like this.

**Pull request merged**
