### PR TITLE
introduce the usage of getrandom

### PR DESCRIPTION
**Pull request by christf**
that will address #24

### CODE REVIEW

**Comment by christf** [comment]
@t-8ch what do you think?

**Comment by t-8ch** [comment]
Looks good!
I would prefer to have the wrapper code in a different source file though.
The while() loop could also be put in its own function.

**Comment by neocturne** [comment]
The `getrandom` function should also use a different name, as it may conflict with a libc-provided implementation like this.

**Comment by t-8ch** [comment]
We should also detect if the kernel does not implement the `getrandom` syscall at all and error out in this case.
(Most probably: `syscall(SYS_getrandom, ...)` returns `-1` and sets `errno` to `ENOSYS`)

**Comment by christf** [comment]
Die Hinweise sind umgesetzt. Was meint ihr?

**Pull request merged**
